### ISSUE TITLE
Feature request : 90° rotation of the screen

### ISSUE THREAD

**Issue by robertrub** [bassettb/SugarPiDisplay#17]
Hi

When you have some time, it would be nice to have the screen rotated 90° and have huge BG numbers and arrow and a small last updated time and drop the graph which is not really useful on this screen (no numbers or reference). 

You'd need to turn the screen _clockwise_ so that the power cable of the Pi Zero will be up and not down and be in the way when the Pi is on a table.. 

Regards.

**Comment by bassettb** [comment]
Sorry, I can't seem to get github to notify me of new issues so I'm just seeing this now.  
I wrote it so each of the screen components is modular and individually drawn, partly so that I could easily rotate it if needed. It was originally horizontal.  I'll work on making it configurable this weekend.

**Comment by bassettb** [comment]
@robertrub I updated the code to support screen rotation.  For now, it still has the graph.  I'll add another option to toggle the graph and expand the BG and arrow.

**Comment by robertrub** [comment]
Hi

Great :) I won't be able to test it yet as I'm on vacation and the Pi is at home but I'll update snd test in 2 weeks.

Have a nice summer.

Rob

----------------------------------------

2 août 2021 15:57:08 bassettb ***@***.***>:

**Comment by robertrub** [comment]
Hi

I updated but something went bad and I no more had any data on the 
paperscreen. I then reinstalled Raspian, reinstalled SugarPi, did the 
settings in SugarPi (NS, NS data, 24h and 90° and save then reboot. The 
screen is still white. I can SSH, I see the RPiZero bbot normally if I 
connect a screen but nothing on the PaperScreen. Even setting the 
rotation to 0° will not work (not even the IP at boot is shown).

Any ideas ? Maybe my PaperScreen is dead ;)

Robert


Le 02/08/2021 à 15:56, bassettb a écrit :

**Comment by bassettb** [comment]
It's not dead, it's just crashing on startup.  I can see why your update would fail.  I'm sorry I didn't catch that before you ran into it.
As for why it failed when you re-did the install, it must be an issue with reading the config file.  I'm looking at it now.

**Comment by bassettb** [comment]
Try doing `git pull` again (or `git pull origin master`) and see if it's fixed now.

**Comment by robertrub** [comment]
Nope, this time, 2 files block the update


 [cid:eu.faircode.email.18804]

----------------------------------------

16 août 2021 22:34:26 bassettb ***@***.***>:

**Comment by robertrub** [comment]
Hi

I deleted the SuparPiDisplay repertory. Went again with the SuparPi 
installation. Still not even a flicker on the PaperScreen.

During the end of the installation process (after install.sh) , I see 
this message, waiting for "q" to quit. I'm not sure if this is normal. I 
didn't have this the very first time I installed SuparPi.



Another strange part is that the configuration for NS access and screen 
orientation is not forgotten when I del the rep. I suppose it is stored 
elsewhere.

Rob


Le 16/08/2021 à 22:34, bassettb a écrit :

**Comment by dentedachiii** [comment]
I had sugarpidisplay running a while ago, and it is awesome, sitting in a little 3d printed case on top of my main screen. Then I had my SD card get corrupted, and set it aside for a while. I just got around to trying to reinstall, and now I cant get the latest version to run. When I get to "SugarPiDisplay/install.sh" I get this:

> pi@raspberrypi:~ $ SugarPiDisplay/install.sh
> ● sugarpidisplay.service - LSB: Starts and stops SugarPiDisplay
>    Loaded: loaded (/etc/init.d/sugarpidisplay; generated)
>    Active: active (running) since Tue 2021-08-24 04:49:10 BST; 30min ago
>      Docs: man:systemd-sysv-generator(8)
>     Tasks: 3 (limit: 877)
>    CGroup: /system.slice/sugarpidisplay.service
>            ├─383 /bin/bash /home/pi/SugarPiDisplay/sugarpidisplay.sh
>            └─387 python3 -m sugarpidisplay
> 
> Aug 24 04:49:06 raspberrypi systemd[1]: Starting LSB: Starts and stops SugarPiDi
> Aug 24 04:49:09 raspberrypi sugarpidisplay[289]: Starting system  daemon:.
> Aug 24 04:49:10 raspberrypi systemd[1]: Started LSB: Starts and stops SugarPiDis
> lines 1-12/12 (END)
> 

The screen displays the IP address and says "Fix Config" and I cant reach the GUI for setup. I assume this is related to the changes for this issue, but apologies if it is not!

**Comment by robertrub** [comment]
Hi

I had the same problem (without the PaperScreen message as mine was not 
activated...) . CTRL-Q (or juste Q I cant recall...) permits to close 
this window. It is some kind of text editor I think. Once you're out all 
worked OK for me

Le 24/08/2021 à 06:25, dentedachiii a écrit :

**Comment by bassettb** [comment]
@dentedachiii Are you running with the old 2-line character display or the newer e-paper display?
I've mostly removed support for the 2-line display, but I could easily add it back in if you'd prefer that.

**Comment by dentedachiii** [comment]
Robertrub, Thanks! I figured that out last night after I posted. 

Bassettb, I am using the e-paper display. 

Thank you both for getting back to me about this. I just fixed it. It was a combination of being confused about the message I posted and then failing to follow directions! I couldnt access the ip address in my browser because I was failing to add ":8080". doh!

Thank you both, sorry for unnecessarily cluttering the thread!

**Comment by robertrub** [comment]
BTW, I "git pull"ed but didn't get the new "without the graph" version. 
Did you update the code yet ? I only have the "old" option in the config 
page.



Le 24/08/2021 à 13:53, bassettb a écrit :

**Comment by bassettb** [comment]
not yet.  Should be up later today.

**Comment by bassettb** [comment]
#18 
#20

**Comment by bassettb** [comment]
@dentedachiii Could you send me images/details on the 3D printed screen enclosure?

**Comment by dentedachiii** [comment]
@bassettb sure. I remixed a case I found on Thingiverse for the same combination of hardware, rotated it so that it would sit vertically, and made a little mount specifically for the old Apple Cinema HD display that I keep on my desktop as the primary display for my MacBook. I posted the stl on thingiverse, but it probably needs to be adjusted for any other screen since this display is remarkable deep: https://www.thingiverse.com/thing:4946362

![IMG_5005](https://user-images.githubusercontent.com/16355532/131579451-9cc9b376-3e4a-45f5-b845-3457932149f5.JPG)

**Comment by robertrub** [comment]
> @dentedachiii Could you send me images/details on the 3D printed screen enclosure?

I bought a metal pi zero case that I use in half ;)

https://www.amazon.fr/KKSB-Raspberry-Zero-Bo%C3%AEtier-Aluminium/dp/B07MFMBW2B
